Update CONTRIBUTING.md
fullstack-hy2020/fullstack-hy2020.github.io pull request #2449
Opened 2023-01-20 20:51 UTC by dragancajic

`required: { node: '>=18.0.0' }`

`$ gatsby`

ERROR  UNKNOWN

Gatsby requires Node.js 18.0.0 or higher (you have v16.14.2).
Upgrade Node to the latest stable release: https://gatsby.dev/upgrading-node-js

2023-01-21 13:14 UTC, mluukkai requested changes

2023-01-21 13:14 UTC, mluukkai commented on CONTRIBUTING.md
> +3. Verify that you are running sufficient Node version ([NVM](https://github.com/nvm-sh/nvm) recommended for managing node versions)
I'd mention there that the proper version is 10...

2023-01-21 17:11 UTC, dragancajic reviewed
Reverted to recommended Node version 10.

2023-01-21 17:20 UTC, dragancajic reviewed
Delete/exclude part0b.md from PR #2449

2023-01-21 21:01 UTC, akirataguchi115 approved these changes
LGTM!

2023-01-22 11:14 UTC, mluukkai requested changes
the pr deletes file part0b.md, and it obviously should not touch that

2023-01-22 19:27 UTC, merged